### PR TITLE
fix client shutdown and push id / stream id confusion

### LINKED ISSUE #174: push ids are not stream ids
The stream id type is used to represent and validate push ids. On GOAWAY frames from the client, `StreamId::is_push()` is used to validate the push id. Based on my understanding of the RFC I believe this is incorrect (they are not related) and it leads to errors on client initiated shutdowns:
```
h3::Error { code: H3_ID_ERROR, reason: "non-push StreamId in a GoAway frame: client bidirectional stream 0" }
```
I can send a PR with the following changes:
- add a PushId type
- Either:
  - differentiate Frame::ServerGoaway(StreamId) and Frame::ClientGoaway(PushId)
  - introduce `GoawayId` with stream and push variants for Frame::Goaway(GoawayId)
  - use Frame::Goaway(u64) and convert to respective type as soon as possible after unpacking

### PR DESCRIPTION
**Pull request by FlorianUekermann**
Fixes #174 and #175

Note: On top of this change ids could use a bit of a clean-up. They aren't used consistently and differ in how well initialization and conversion are protected from creating invalid values etc. But that is beyond the scope of this PR, I would like to address that in a follow-up.

### CODE REVIEW

File: h3/src/connection.rs [hunk 1]
```diff
@@ -460,8 +433,43 @@ where
...
+                        Code::H3_ID_ERROR,
+                        format!(
+                            "received a GoAway({}) greater than the former one ({})",
+                            id, prev_id
+                        ),
+                    ));
+                }
+            }
+            *recv_closing = Some(id.into());
+            Ok(())
```
Comment (Ruben2424) [inline h3/src/connection.rs:471]: Thanks for this awesome PR.

I just got one question, do we need a additional `self.shared.write("connection goaway write").closing = true;` here?

Comment (FlorianUekermann) [reply h3/src/connection.rs:471]: No we don't. This is done on frame receipt on connection level in poll_control (same file L378). That prevented duplication before I merged the client and server side code in the generic `process_goaway`. Maybe I should move it to the place you suggested to keep those things closer together like it is done on shutdown. Let me know what you think. I'm slightly in favor of moving it.

File: h3/src/client.rs [hunk 2]
```diff
@@ -420,22 +429,18 @@ where
...
-                            self.inner.shared.write("poll_close error").error = e.clone().into();
-                            return Poll::Ready(Err(e));
+                            self.inner.shared.write("poll_close error").error = Some(e.clone());
+                            e
                         }
+                    };
+                    if connection_error.is_closed() {
+                        return Poll::Ready(Ok(()));
                     }
+                    return Poll::Ready(Err(connection_error));
```
Comment (FlorianUekermann) [inline h3/src/client.rs:443]: I think: This fixes a preexisting bug, which wasn't discovered due to the lack of test coverage of client shutdown (cases where the server closes the connection without error). Basically, if the server closes, the first time the resulting error on the client is seen, the old code does the match on the previous error in `self.inner.shared.error` (which is `None`), thus skipping the arm that leads to `Ok(())`.

The only way I could make this make sense to me was that the intention of this piece of code is to match on the first error, but got the order of doing things confused.
So I did the equivalent to `let connection_error = self.inner.shared.write("poll_close").error.get_or_insert(e)` but without taking the write lock if not necessary.

Did I misunderstand the original intent here?

File: h3/src/proto/frame.rs [hunk 3]
```diff
@@ -30,19 +32,20 @@ impl fmt::Display for FrameError {
...
 pub enum Frame<B> {
     Data(B),
     Headers(Bytes),
-    CancelPush(StreamId),
+    CancelPush(PushId),
     Settings(Settings),
     PushPromise(PushPromise),
-    Goaway(StreamId),
-    MaxPushId(StreamId),
+    Goaway(VarInt),
```
Comment (FlorianUekermann) [inline h3/src/proto/frame.rs:47]: Just a note: Initially I tried to go for `Frame::Goaway(Goaway)`, where `Goaway` is an enum with `Server` and `Client` variants, as you suggested initially. From a type design perspective I still think that is a little better. But that introduces a dependency on the information whether we are parsing a server or client frame in the frame parser, which in turn infects a few functions and types further up the call-chain, which didn't feel worth it.

File: h3/src/connection.rs (hunk 1 above)
Comment (Ruben2424) [reply h3/src/connection.rs:471]: Oh I missed that. 
But I am also thinking that it could be slightly better to move it.

File: h3/src/proto/frame.rs (hunk 3 above)
Comment (Ruben2424) [reply h3/src/proto/frame.rs:47]: Thats ok for me.

File: h3/src/client.rs (hunk 2 above)
Comment (Ruben2424) [reply h3/src/client.rs:443]: I do not know what the original intention was. But the change makes sense to me.

Comment (seanmonstar) [reply h3/src/client.rs:443]: > the lack of test coverage of client shutdown

Thanks for helping to add some, more tests is love! <3

File: h3/src/connection.rs (hunk 1 above)
Comment (FlorianUekermann) [reply h3/src/connection.rs:469]: done
